# Generated by Django 5.2.5 on 2025-10-04 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=40)),
                ('nom', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('centre', models.CharField(choices=[('CBRG', 'Centre Bureautique Reseau Global'), ('KAY', 'Kayes'), ('GAO', 'Gao')], max_length=100)),
                ('motif', models.TextField(max_length=255)),
                ('quantite', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attri', models.DateTimeField(auto_now_add=True)),
                ('ref', models.CharField(blank=True, max_length=20, null=True)),
                ('prenom', models.CharField(blank=True, max_length=40, null=True)),
                ('nom', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(blank=True, choices=[('DG', 'Direction Générale'), ('DRH', 'Direction Ressources Humaines'), ('DAF', 'Direction Administratif Financier'), ('DIS', 'Direction Infrastructure Système'), ('DCO', 'Direction Commerciale')], max_length=100, null=True)),
                ('departement', models.CharField(blank=True, choices=[('DSI', 'Département Système Information'), ('DRF', 'Département Réseaux Fixe'), ('DRM', 'Département Réseaux Mobile')], max_length=100, null=True)),
                ('service', models.CharField(blank=True, choices=[('SPI', 'Service Production Informatique'), ('SIS', 'Systèmes'), ('SUP', 'Support')], max_length=100, null=True)),
                ('locality', models.CharField(blank=True, max_length=20, null=True)),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('etat', models.CharField(choices=[('bon', 'BON'), ('pass', 'PASSABLE'), ('endo', 'ENDOMMAGER')], default='bon', max_length=20)),
                ('approvisionnement', models.ForeignKey(blank=True, help_text='Approvisionnement dont provient le matériel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_app.approvisionnement')),
                ('demande', models.ForeignKey(blank=True, help_text='Demande à l’origine de cette attribution', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_app.demande')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_app.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='demande',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.departement'),
        ),
        migrations.AddField(
            model_name='departement',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='stock_app.direction'),
        ),
        migrations.AddField(
            model_name='demande',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.direction'),
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricant', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('modal', models.CharField(default='modèle', max_length=100)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.categorie')),
            ],
        ),
        migrations.AddField(
            model_name='demande',
            name='materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.materiel'),
        ),
        migrations.CreateModel(
            name='AttribuMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('attri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.attribution')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.materiel')),
            ],
        ),
        migrations.CreateModel(
            name='ApproMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('appro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.approvisionnement')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='stock_app.departement')),
            ],
        ),
        migrations.AddField(
            model_name='demande',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.service'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.materiel')),
            ],
        ),
        migrations.AddField(
            model_name='approvisionnement',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_app.utilisateur'),
        ),
    ]
