# Generated by Django 5.2.5 on 2025-09-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_approvisionnement_utilisateur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantite',
            new_name='quantite_stock',
        ),
    ]
