# Generated by Django 5.2.5 on 2025-10-06 09:36

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_alter_attribution_departement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='centre',
        ),
        migrations.AddField(
            model_name='demande',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
