# Generated by Django 5.2.5 on 2025-09-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0003_rename_quantite_stock_quantite_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantite_stock',
            new_name='quantite',
        ),
    ]
