# Generated by Django 5.2.5 on 2025-09-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0004_rename_quantite_stock_stock_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='modal',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='materiel',
            name='serie',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
