# Generated by Django 5.2.5 on 2025-09-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0005_materiel_modal_materiel_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='demandeur',
        ),
        migrations.AddField(
            model_name='demande',
            name='centre',
            field=models.TextField(default='inconnu', max_length=10),
        ),
        migrations.AddField(
            model_name='demande',
            name='departement',
            field=models.TextField(default='inconnu', max_length=10),
        ),
        migrations.AddField(
            model_name='demande',
            name='direction',
            field=models.TextField(default='inconnu', max_length=10),
        ),
        migrations.AddField(
            model_name='demande',
            name='email',
            field=models.EmailField(default='admin@moov-africa.sotelma', max_length=50),
        ),
        migrations.AddField(
            model_name='demande',
            name='nom',
            field=models.CharField(default='inconnu', max_length=40),
        ),
        migrations.AddField(
            model_name='demande',
            name='prenom',
            field=models.CharField(default='inconnu', max_length=40),
        ),
        migrations.AddField(
            model_name='demande',
            name='service',
            field=models.TextField(default='inconnu', max_length=10),
        ),
    ]
