# Generated by Django 5.2.5 on 2025-09-09 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0006_remove_demande_demandeur_demande_centre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='password',
        ),
    ]
