# Generated by Django 5.2.5 on 2025-09-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0007_remove_utilisateur_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='motif',
            field=models.TextField(default='obligatoire', max_length=255),
        ),
    ]
