# Generated by Django 5.2.5 on 2025-09-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0008_demande_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='ref',
            field=models.TextField(default='La référence', max_length=20),
        ),
        migrations.AddField(
            model_name='attribution',
            name='usager',
            field=models.CharField(default='usager', max_length=50),
        ),
        migrations.AlterField(
            model_name='demande',
            name='centre',
            field=models.TextField(default='centre', max_length=10),
        ),
        migrations.AlterField(
            model_name='demande',
            name='departement',
            field=models.TextField(default='departement', max_length=10),
        ),
        migrations.AlterField(
            model_name='demande',
            name='direction',
            field=models.TextField(default='direction', max_length=10),
        ),
        migrations.AlterField(
            model_name='demande',
            name='motif',
            field=models.TextField(default='motif', max_length=255),
        ),
        migrations.AlterField(
            model_name='demande',
            name='nom',
            field=models.CharField(default='nom', max_length=40),
        ),
        migrations.AlterField(
            model_name='demande',
            name='prenom',
            field=models.CharField(default='prenom', max_length=40),
        ),
        migrations.AlterField(
            model_name='demande',
            name='service',
            field=models.TextField(default='service', max_length=10),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='modal',
            field=models.CharField(default='modèle', max_length=100),
        ),
    ]
