# Generated by Django 5.2.5 on 2025-09-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0009_attribution_ref_attribution_usager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appromateriel',
            name='materiel',
        ),
        migrations.AddField(
            model_name='appromateriel',
            name='materiel',
            field=models.ManyToManyField(to='stock_app.materiel'),
        ),
    ]
