# Generated by Django 5.2.5 on 2025-09-10 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0010_remove_appromateriel_materiel_appromateriel_materiel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appromateriel',
            name='materiel',
        ),
        migrations.AddField(
            model_name='appromateriel',
            name='materiel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock_app.materiel'),
        ),
    ]
