# Generated by Django 5.2.5 on 2025-09-10 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0011_remove_appromateriel_materiel_appromateriel_materiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appromateriel',
            name='materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.materiel'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='serie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
