# Generated by Django 5.2.5 on 2025-09-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0012_alter_appromateriel_materiel_alter_materiel_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribution',
            name='ref',
            field=models.CharField(default='La référence', max_length=20),
        ),
        migrations.AlterField(
            model_name='demande',
            name='centre',
            field=models.CharField(default='centre', max_length=10),
        ),
        migrations.AlterField(
            model_name='demande',
            name='departement',
            field=models.CharField(default='departement', max_length=10),
        ),
        migrations.AlterField(
            model_name='demande',
            name='direction',
            field=models.CharField(default='direction', max_length=10),
        ),
        migrations.AlterField(
            model_name='demande',
            name='service',
            field=models.CharField(default='service', max_length=10),
        ),
    ]
