# Generated by Django 5.2.5 on 2025-09-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0013_alter_attribution_ref_alter_demande_centre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='centre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='demande',
            name='departement',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='demande',
            name='direction',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='demande',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='demande',
            name='motif',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='demande',
            name='nom',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='demande',
            name='prenom',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='demande',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
