# Generated by Django 5.2.5 on 2025-09-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0014_alter_demande_centre_alter_demande_departement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribution',
            name='ref',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='usager',
            field=models.CharField(max_length=50),
        ),
    ]
