# Generated by Django 5.2.5 on 2025-09-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0015_alter_attribution_ref_alter_attribution_usager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='centre',
            field=models.CharField(choices=[('BKO', 'Bamako'), ('KAY', 'Kayes'), ('GAO', 'Gao')], max_length=100),
        ),
        migrations.AlterField(
            model_name='demande',
            name='departement',
            field=models.CharField(choices=[('DEV', 'Développement'), ('NET', 'Réseaux'), ('SEC', 'Sécurité')], max_length=100),
        ),
        migrations.AlterField(
            model_name='demande',
            name='direction',
            field=models.CharField(choices=[('IT', 'Informatique'), ('RH', 'Ressources Humaines'), ('FIN', 'Finance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='demande',
            name='service',
            field=models.CharField(choices=[('APP', 'Applications'), ('SIS', 'Systèmes'), ('SUP', 'Support')], max_length=100),
        ),
    ]
