# Generated by Django 5.2.5 on 2025-09-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0016_alter_demande_centre_alter_demande_departement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='centre',
            field=models.CharField(choices=[('CBRG', 'Centre Bureautique Reseau Global'), ('KAY', 'Kayes'), ('GAO', 'Gao')], max_length=100),
        ),
        migrations.AlterField(
            model_name='demande',
            name='departement',
            field=models.CharField(choices=[('DSI', 'Département Système Information'), ('DRF', 'Département Réseaux Fixe'), ('DRM', 'Département Réseaux Mobile')], max_length=100),
        ),
        migrations.AlterField(
            model_name='demande',
            name='direction',
            field=models.CharField(choices=[('DG', 'Direction Générale'), ('DRH', 'Direction Ressources Humaines'), ('DAF', 'Direction Administratif Financier'), ('DIS', 'Direction Infrastructure Système'), ('DCO', 'Direction Commerciale')], max_length=100),
        ),
        migrations.AlterField(
            model_name='demande',
            name='service',
            field=models.CharField(choices=[('SPI', 'Service Production Informatique'), ('SIS', 'Systèmes'), ('SUP', 'Support')], max_length=100),
        ),
    ]
