# Generated by Django 5.2.5 on 2025-09-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0017_alter_demande_centre_alter_demande_departement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='usager',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='serie',
        ),
        migrations.AddField(
            model_name='attribution',
            name='departement',
            field=models.CharField(blank=True, choices=[('DSI', 'Département Système Information'), ('DRF', 'Département Réseaux Fixe'), ('DRM', 'Département Réseaux Mobile')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attribution',
            name='direction',
            field=models.CharField(blank=True, choices=[('DG', 'Direction Générale'), ('DRH', 'Direction Ressources Humaines'), ('DAF', 'Direction Administratif Financier'), ('DIS', 'Direction Infrastructure Système'), ('DCO', 'Direction Commerciale')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attribution',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attribution',
            name='etat',
            field=models.CharField(choices=[('bon', 'BON'), ('pass', 'PASSABLE'), ('endo', 'ENDOMMAGER')], default='bon', max_length=20),
        ),
        migrations.AddField(
            model_name='attribution',
            name='locality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attribution',
            name='nom',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='attribution',
            name='prenom',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='attribution',
            name='serie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attribution',
            name='service',
            field=models.CharField(blank=True, choices=[('SPI', 'Service Production Informatique'), ('SIS', 'Systèmes'), ('SUP', 'Support')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='ref',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
