# Generated by Django 5.2.5 on 2025-10-02 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0018_remove_attribution_usager_remove_materiel_serie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='approvisionnement',
            field=models.ForeignKey(blank=True, help_text='Approvisionnement dont provient le matériel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_app.approvisionnement'),
        ),
        migrations.AddField(
            model_name='attribution',
            name='demande',
            field=models.ForeignKey(blank=True, help_text='Demande à l’origine de cette attribution', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_app.demande'),
        ),
    ]
