# Generated by Django 5.2.5 on 2025-10-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0019_attribution_approvisionnement_attribution_demande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='demande',
        ),
        migrations.AddField(
            model_name='attribution',
            name='type',
            field=models.CharField(choices=[('demande', 'DEMANDE'), ('dotation', 'DOTATION')], default='demande', max_length=20),
        ),
    ]
