# Generated by Django 5.2.5 on 2025-10-03 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0020_remove_attribution_demande_attribution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribution',
            name='approvisionnement',
            field=models.ForeignKey(blank=True, help_text='Approvisionnement dont provient le matériel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_app.appromateriel'),
        ),
    ]
