# Generated by Django 5.2.5 on 2025-10-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0022_remove_attribumateriel_materiel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='service',
        ),
    ]
