# Generated by Django 5.2.5 on 2025-10-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0023_remove_attribution_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribumateriel',
            name='materiel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_app.materiel'),
        ),
    ]
