# Generated by Django 5.2.5 on 2025-10-03 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0024_attribumateriel_materiel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribumateriel',
            name='appro',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='type',
        ),
        migrations.AddField(
            model_name='attribution',
            name='demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_app.demande'),
        ),
        migrations.AddField(
            model_name='attribution',
            name='service',
            field=models.CharField(blank=True, choices=[('SPI', 'Service Production Informatique'), ('SIS', 'Systèmes'), ('SUP', 'Support')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attribumateriel',
            name='materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.materiel'),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='approvisionnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_app.approvisionnement'),
        ),
    ]
