# Generated by Django 5.2.5 on 2025-10-03 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0025_remove_attribumateriel_appro_remove_attribution_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribumateriel',
            name='materiel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_app.materiel'),
        ),
    ]
