# Generated by Django 5.2.5 on 2025-10-03 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0026_alter_attribumateriel_materiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribumateriel',
            name='materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.materiel'),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='approvisionnement',
            field=models.ForeignKey(blank=True, help_text='Approvisionnement dont provient le matériel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_app.approvisionnement'),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='demande',
            field=models.ForeignKey(blank=True, help_text='Demande à l’origine de cette attribution', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_app.demande'),
        ),
    ]
